# Generated by Django 5.2.6 on 2025-09-19 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("front", "Вид спереди"),
                            ("back", "Вид сзади"),
                            ("side", "Вид сбоку"),
                            ("scale", "Показания весов"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("user", "photo_type")},
            },
        ),
        migrations.CreateModel(
            name="BodyCompositionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_body_fat", models.FloatField(blank=True, null=True)),
                ("estimated_muscle_mass", models.FloatField(blank=True, null=True)),
                ("visceral_fat_level", models.IntegerField(blank=True, null=True)),
                ("metabolic_age", models.IntegerField(blank=True, null=True)),
                ("bone_mass", models.FloatField(blank=True, null=True)),
                ("water_percentage", models.FloatField(blank=True, null=True)),
                ("body_shape_type", models.CharField(blank=True, max_length=20)),
                ("problem_areas", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "measurements",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.bodymeasurements",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weight_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.weightlog",
                    ),
                ),
                (
                    "front_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_analysis.photoupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostureAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoulder_slope_degrees", models.FloatField(blank=True, null=True)),
                ("hip_slope_degrees", models.FloatField(blank=True, null=True)),
                ("knee_valgus_angle", models.FloatField(blank=True, null=True)),
                ("head_tilt_degrees", models.FloatField(blank=True, null=True)),
                ("front_keypoints", models.JSONField(blank=True, default=dict)),
                ("back_keypoints", models.JSONField(blank=True, default=dict)),
                ("posture_score", models.FloatField(blank=True, null=True)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "back_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_analyses",
                        to="ai_analysis.photoupload",
                    ),
                ),
                (
                    "front_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="front_analyses",
                        to="ai_analysis.photoupload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exercise", "Упражнения"),
                            ("nutrition", "Питание"),
                            ("posture", "Осанка"),
                            ("lifestyle", "Образ жизни"),
                            ("recovery", "Восстановление"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("action_steps", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "body_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_analysis.bodycompositionanalysis",
                    ),
                ),
                (
                    "posture_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_analysis.postureanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("weight_change", models.FloatField(blank=True, null=True)),
                ("body_fat_change", models.FloatField(blank=True, null=True)),
                ("muscle_mass_change", models.FloatField(blank=True, null=True)),
                ("waist_change", models.FloatField(blank=True, null=True)),
                ("hip_change", models.FloatField(blank=True, null=True)),
                ("posture_score_change", models.FloatField(blank=True, null=True)),
                ("achievements", models.JSONField(default=list)),
                ("milestones_reached", models.JSONField(default=list)),
                ("overall_progress_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("strength", "Силовая"),
                            ("cardio", "Кардио"),
                            ("flexibility", "Гибкость"),
                            ("balance", "Баланс"),
                            ("rehabilitation", "Реабилитация"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Начинающий"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("exercises", models.JSONField(default=list)),
                ("equipment_needed", models.JSONField(default=list)),
                ("target_muscle_groups", models.JSONField(default=list)),
                (
                    "calories_burned_estimate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "based_on_body_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_analysis.bodycompositionanalysis",
                    ),
                ),
                (
                    "based_on_posture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_analysis.postureanalysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
